version: "3.8"                                                # версия docker-compose формата

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0                    # ZooKeeper (нужен для cp-kafka в этом режиме)
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181                             # порт ZooKeeper
      ZOOKEEPER_TICK_TIME: 2000                               # тик ZooKeeper (дефолт/ок)
    ports:
      - "2181:2181"                                           # проброс порта на хост

  kafka:
    image: confluentinc/cp-kafka:7.5.0                        # Kafka broker (Confluent Platform)
    container_name: kafka
    depends_on:
      - zookeeper                                             # сначала должен стартануть zookeeper
    ports:
      - "9092:9092"                                           # внешний порт для хоста (localhost:9092)
    environment:
      KAFKA_BROKER_ID: 1                                      # id брокера (у нас один)
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"               # подключение к ZooKeeper внутри сети docker

      # 2 listener-а: INTERNAL для контейнеров, EXTERNAL для хоста
      KAFKA_LISTENERS: "INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092"     # где слушаем
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092" # как рекламируем адреса клиентам
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"  # протоколы
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"            # брокеры общаются через INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1               # offsets topic RF=1 (один брокер)

      # EOS (Exactly-Once) для ОДНОГО брокера
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1        # tx state topic RF=1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1                   # min ISR=1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest                    # простая UI для Kafka
    container_name: kafdrop
    depends_on:
      - kafka
    ports:
      - "9000:9000"                                           # UI: http://localhost:9000
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"                      # подключаемся к Kafka по INTERNAL listener
      JVM_OPTS: "-Xms64m -Xmx256m"                             # ограничение памяти
    restart: unless-stopped

  redpanda-console:
    image: redpandadata/console:latest                        # ещё одна UI (Redpanda Console)
    container_name: redpanda-console
    depends_on:
      - kafka
    ports:
      - "8089:8080"                                           # UI: http://localhost:8089
    environment:
      KAFKA_BROKERS: "kafka:29092"                             # подключаемся по INTERNAL
    restart: unless-stopped

  akhq:
    image: tchiotludo/akhq:latest                             # AKHQ UI
    container_name: akhq
    depends_on:
      - kafka
    ports:
      - "8088:8080"                                           # UI: http://localhost:8088
    environment:
      AKHQ_CONFIGURATION: |                                   # конфиг прямо строкой
        akhq:
          connections:
            local-kafka:
              properties:
                bootstrap.servers: "kafka:29092"              # подключение к Kafka по INTERNAL listener
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: kafka_outbox            # база
      POSTGRES_USER: outbox                # пользователь
      POSTGRES_PASSWORD: outbox            # пароль
    ports:
      - "5432:5432"                        # Postgres на хост: localhost:5432
    volumes:
      - pgdata_outbox:/var/lib/postgresql/data              # данные БД (persist)
      - ./postgres/init:/docker-entrypoint-initdb.d  # init SQL (схемы/права) при первом старте volume
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U outbox -d kafka_outbox"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"                          # UI: http://localhost:5050
    depends_on:
      - postgres
    restart: unless-stopped

#    Вход: http://localhost:5050  admin@admin.com / admin
#
#    Подключение к Postgres внутри docker-сети:
#    Host: postgres
#    Port: 5432
#    DB: kafka_outbox
#    User/Pass: outbox / outbox

volumes:
  pgdata_outbox:                            # именованный volume для Postgres
