server:
  port: 8083

app:
  kafka:
    topic: guarantee-at-least-once-topic
#    group-id: guarantee-at-least-once-group
    group-id: guarantee-at-least-once-group-v2

spring:
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: ${app.kafka.group-id} # –≥—Ä—É–ø–ø–∞ –∫–æ–Ω—Å—é–º–µ—Ä–∞
      auto-offset-reset: earliest     # –¥–ª—è –¥–µ–º–æ —á–∏—Ç–∞–µ–º "—Å –Ω–∞—á–∞–ª–∞", –µ—Å–ª–∏ –æ—Ñ—Å–µ—Ç–∞ –Ω–µ—Ç
      enable-auto-commit: false       # –∞–≤—Ç–æ-–∫–æ–º–º–∏—Ç –≤—ã–∫–ª—é—á–µ–Ω (–º—ã –∫–æ–º–º–∏—Ç–∏–º ACK'–æ–º)
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"     # —Ä–∞–∑—Ä–µ—à–∞–µ–º –¥–µ—Å–µ—Ä–∏–∞–ª–∏–∑–∞—Ü–∏—é DTO

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    listener:
      ack-mode: manual # –í–ê–ñ–ù–û: –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–∞–µ–º offset –≤—Ä—É—á–Ω—É—é —á–µ—Ä–µ–∑ Acknowledgment.acknowledge()

  datasource:
    url: jdbc:h2:mem:alo2;DB_CLOSE_DELAY=-1       # üëà in-memory –ë–î (–∂–∏–≤–µ—Ç –ø–æ–∫–∞ –ø—Ä–∏–ª–æ–∂–µ–Ω–∏–µ –∂–∏–≤–æ)
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update                           # üëà –¥–ª—è –¥–µ–º–æ –æ–∫
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console                          # üëà http://localhost:8083/h2-console
